"""empty message

Revision ID: a236fd9343df
Revises: 14be63a7a427
Create Date: 2025-07-25 02:53:10.039990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a236fd9343df'
down_revision: Union[str, None] = '14be63a7a427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positions', 'owner',
               existing_type=sa.VARCHAR(length=42),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positions', 'owner',
               existing_type=sa.VARCHAR(length=42),
               nullable=False)
    # ### end Alembic commands ###
