"""empty message

Revision ID: ac854e537536
Revises: 7079e890281b
Create Date: 2025-07-30 14:53:13.886560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac854e537536'
down_revision: Union[str, None] = '7079e890281b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('frozen_by', sa.String(length=42), nullable=True, comment='Address of the liquidator who froze the position'))
    op.add_column('positions', sa.Column('frozen_time', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the position was frozen by a liquidator'))
    op.create_index(op.f('ix_positions_positions_frozen_by'), 'positions', ['frozen_by'], unique=False)
    op.create_index(op.f('ix_positions_positions_frozen_time'), 'positions', ['frozen_time'], unique=False)
    op.drop_column('positions', 'owner')
    op.drop_column('positions', 'open')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('open', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('positions', sa.Column('owner', sa.VARCHAR(length=42), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_positions_positions_frozen_time'), table_name='positions')
    op.drop_index(op.f('ix_positions_positions_frozen_by'), table_name='positions')
    op.drop_column('positions', 'frozen_time')
    op.drop_column('positions', 'frozen_by')
    # ### end Alembic commands ###
