"""empty message

Revision ID: 14be63a7a427
Revises: 
Create Date: 2025-07-25 00:48:10.277666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14be63a7a427'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pools',
    sa.Column('id', sa.String(length=42), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pools'))
    )
    op.create_table('positions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('owner', sa.String(length=42), nullable=False),
    sa.Column('open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions'))
    )
    op.create_table('position_pool',
    sa.Column('position_id', sa.BigInteger(), nullable=False),
    sa.Column('pool_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], name=op.f('fk_position_pool_pool_id_pools')),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_position_pool_position_id_positions')),
    sa.PrimaryKeyConstraint('position_id', 'pool_id', name=op.f('pk_position_pool'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position_pool')
    op.drop_table('positions')
    op.drop_table('pools')
    # ### end Alembic commands ###
