"""empty message

Revision ID: 8186b98cd113
Revises: ac854e537536
Create Date: 2025-07-30 14:55:38.150748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8186b98cd113'
down_revision: Union[str, None] = 'ac854e537536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_position_pool_pool_id_pools'), 'position_pool', type_='foreignkey')
    op.drop_constraint(op.f('fk_position_pool_position_id_positions'), 'position_pool', type_='foreignkey')
    op.create_foreign_key(op.f('fk_position_pool_pool_id_pools'), 'position_pool', 'pools', ['pool_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_position_pool_position_id_positions'), 'position_pool', 'positions', ['position_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_position_pool_position_id_positions'), 'position_pool', type_='foreignkey')
    op.drop_constraint(op.f('fk_position_pool_pool_id_pools'), 'position_pool', type_='foreignkey')
    op.create_foreign_key(op.f('fk_position_pool_position_id_positions'), 'position_pool', 'positions', ['position_id'], ['id'])
    op.create_foreign_key(op.f('fk_position_pool_pool_id_pools'), 'position_pool', 'pools', ['pool_id'], ['id'])
    # ### end Alembic commands ###
