"""empty message

Revision ID: 117f16564d64
Revises: 8186b98cd113
Create Date: 2025-08-01 15:10:33.253394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '117f16564d64'
down_revision: Union[str, None] = '8186b98cd113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pools', 'id',
               existing_type=sa.VARCHAR(length=42),
               comment='Unique identifier for the pool (address)',
               existing_nullable=False)
    op.add_column('positions', sa.Column('is_liquidated', sa.Boolean(), nullable=True, comment='Indicates if the position has been liquidated'))
    op.create_index(op.f('ix_positions_positions_is_liquidated'), 'positions', ['is_liquidated'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_positions_is_liquidated'), table_name='positions')
    op.drop_column('positions', 'is_liquidated')
    op.alter_column('pools', 'id',
               existing_type=sa.VARCHAR(length=42),
               comment=None,
               existing_comment='Unique identifier for the pool (address)',
               existing_nullable=False)
    # ### end Alembic commands ###
