"""empty message

Revision ID: a906ce7ebfa0
Revises: d03432c86e42
Create Date: 2025-09-04 23:28:21.150692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a906ce7ebfa0'
down_revision: Union[str, None] = 'd03432c86e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_positions_frozen_by'), table_name='positions')
    op.drop_index(op.f('ix_positions_positions_frozen_time'), table_name='positions')
    op.create_index(op.f('ix_positions_positions_predict_check_timestamp'), 'positions', ['predict_check_timestamp'], unique=False)
    op.drop_column('positions', 'frozen_time')
    op.drop_column('positions', 'frozen_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('frozen_by', sa.VARCHAR(length=42), autoincrement=False, nullable=True, comment='Address of the liquidator who froze the position'))
    op.add_column('positions', sa.Column('frozen_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Timestamp when the position was frozen by a liquidator'))
    op.drop_index(op.f('ix_positions_positions_predict_check_timestamp'), table_name='positions')
    op.create_index(op.f('ix_positions_positions_frozen_time'), 'positions', ['frozen_time'], unique=False)
    op.create_index(op.f('ix_positions_positions_frozen_by'), 'positions', ['frozen_by'], unique=False)
    # ### end Alembic commands ###
