"""empty message

Revision ID: d03432c86e42
Revises: 117f16564d64
Create Date: 2025-08-29 15:58:17.295434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd03432c86e42'
down_revision: Union[str, None] = '117f16564d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('predict_check_timestamp', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'predict_check_timestamp')
    # ### end Alembic commands ###
